build forec

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -21,6 +21,7 @@ jobs:
         run: echo "npm version:{{ $NPM_VERSION}}"
       - name: Use repo variable
         run: echo "test URL:{{ vars.TEST_URL}}"
+
       - name: Clone repo
         uses: actions/checkout@v5
       - name: Get npm cache directory
@@ -47,9 +48,17 @@ jobs:
         with:
           name: dist-folder
           path: dist/
+        # บังคับให้ออก เพื่อให้ build fail
+      - name: Forece fail
+        run: exit 1
 
   deploy:
-    if: ${{ github.ref == 'refs/heads/main' }}
+    # ทำงานเมื่อ branchrefs/heads/main
+    # if: ${{ github.ref == 'refs/heads/main' }}
+
+    # ทำงานเมื่อ job ข้างบนสำเร็จ ให้ไปทำ notifyต่อ     # check ใน  needs ทั้งหมด ว่า success ไหม ถ้าผ่านทั้งหมด
+    if: ${{ success() }}
+
     # needs:
     #   - lint
     runs-on: ubuntu-latest
@@ -70,3 +79,16 @@ jobs:
         run: ls dist
       - name: Deploy
         run: echo "Deployedssss.."
+  notify:
+    runs-on: ubuntu-latest
+    needs:
+      - build
+      # check ใน  needs ทั้งหมด ว่า fail ไหม ถ้ามีfail จะทำงาน(มี1อันก็ทำงาน)
+    if: failure()
+    steps:
+      - name: Notify Discord noti
+        env:
+          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1421697869458706533/W2UqZa7gD95EU7ixa4gQN3QLz3pWc3oFepvpv16XWxfpuMMTTiqbNULZWrBBmPfPlYBY
+        uses: Ilshidur/action-discord@master
+        with:
+          args: "build has been deployed."
